AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DomainName:
    Type: String
  GithubRepo:
    Type: String
    Default: https://github.com/username/repository.git
  GitHubAccessToken:
    Type: String
    Default: '{{resolve:secretsmanager:github-access-token-santerisalonen:SecretString:GithubAccessToken}}'

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties: 
      AccessToken: !Ref GitHubAccessToken
      Repository: !Ref GithubRepo
      #AutoBranchCreationConfig: 
      #  AutoBranchCreationConfig
      #BasicAuthConfig: 
      #  BasicAuthConfig
      BuildSpec: |-
        version: 1
        frontend:
          phases:
            build:
              commands:
                - cd ./
          artifacts:
            baseDirectory: frontend/public/
            files:
<<<<<<< HEAD
              - 'frontend/public/*/**'
=======
              - '*/**'
>>>>>>> ed4cdd6b840e7525894fa851205844e5e847ccfa
      #CustomRules: 
      #  - CustomRule
      #Description: String
      #EnvironmentVariables: 
      #  - EnvironmentVariable
      #IAMServiceRole: String
      Name: Amplify Test CF
      #OauthToken: String
      #Tags: 
      #  - Tag


  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: master
      AppId: !GetAtt AmplifyApp.AppId
      Description: Master Branch
      EnableAutoBuild: true

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: !Ref DomainName
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - Prefix: master
          BranchName: !GetAtt AmplifyBranch.BranchName

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain

  MasterBranchUrl:
    Value: !Join [ ".", [ !GetAtt AmplifyBranch.BranchName, !GetAtt AmplifyDomain.DomainName ]]
